#Copyright (c) Gilljan 2020-2022. All rights reserved.
#Plugin written by Gilljan
Prefix: '&eGWorld &8┃ &7' #prefix of the plugin
Language: 'EN' #avaiable languages: german (de), english (en)
MainWorld: 'world' #while deleting a world the players which are on the world will be teleported to this world

#Update-Notifications
UpdateNotification: true

#AutoImporter
AutoImport: true #deactivate to stop import of maps provided by other systems

#Default world-template
World:
  timeCycle: true
  time: 6000
  weatherCycle: true
  weather: sun
  pvp: true
  mobs: true
  animals: true
  forcedGamemode: false
  defaultGamemode: SURVIVAL
  difficulty: NORMAL
  randomTickSpeed: 3
  announceAdvancements: true