name: GWorld
version: 1.0.2
main: de.gilljan.gworld.Main

author: Gilljan
description: GWorld System - MapSystem

database: false
load: POSTWORLD

commands:
  gcreate:
  gimport:
  gtp:
  gclone:
  gdelete:
  gworlds:
  gwreload:
  gset:
  ginfo:
  grecreate:
  gunload:
  gload:

permissions:
  gworld.*:
    default: op
    description: Allows you to get all permissions in one.
    children:
      gworld.import: true
      gworld.create: true
      gworld.clone: true
      gworld.delete: true
      gworld.info: true
      gworld.teleport: true
      gworld.set: true
      gworld.worlds: true
      gworld.reload: true
      gworld.version: true
      gworld.recreate: true
      gworld.unload: true
      gworld.load: true

